// ENV
const CONSTANT_ENVIRONMENT_DEV = 'DEV';
const CONSTANT_ENVIRONMENT_RELEASE = 'RELEASE';
const CONSTANT_APP_NAME = 'APP_NAME';
const CONSTANT_IS_DEBUG = 'IS_DEBUG';

// LOCALE
const CONSTANT_STORE_LOCALE = 'LOCALE';

// LOCALES
const CONSTANT_LOCALES_EN = 'assets/locales/en.json';
const CONSTANT_LOCALES_VI = 'assets/locales/vi.json';

const CONSTANT_ERROR_SOMETHING_WROMG = 'ERROR_SOMETHING_WROMG';
const CONSTANT_LOGIN_SCREEN_NAME_HEADER = 'LOGIN_SCREEN_NAME_HEADER';
const CONSTANT_LOGIN_SCREEN_TITLE_USERNAME = 'LOGIN_SCREEN_TITLE_USERNAME';
const CONSTANT_LOGIN_SCREEN_TITLE_PASSWORD = 'LOGIN_SCREEN_TITLE_PASSWORD';
const CONSTANT_LOGIN_SCREEN_TITLE_REMEMBERME = 'LOGIN_SCREEN_TITLE_REMEMBERME';
const CONSTANT_LOGIN_SCREEN_TITLE_FORGOT_PASSWORD =
    'LOGIN_SCREEN_TITLE_FORGOT_PASSWORD';
const CONSTANT_LOGIN_SCREEN_NAME_BUTTON_LOGIN =
    'LOGIN_SCREEN_NAME_BUTTON_LOGIN';
const CONSTANT_LOGIN_SCREEN_TITLE_DONT_HAVE_AN_ACCOUNT_YET =
    'LOGIN_SCREEN_TITLE_DONT_HAVE_AN_ACCOUNT_YET';
const CONSTANT_LOGIN_SCREEN_TITLE_SIGN_UP_NOW =
    'LOGIN_SCREEN_TITLE_SIGN_UP_NOW';
const CONSTANT_LOGIN_SCREEN_USERNAME_NOT_NULL_OR_EMPTY =
    'LOGIN_SCREEN_USERNAME_NOT_NULL_OR_EMPTY';
const CONSTANT_LOGIN_SCREEN_PASSWORD_NOT_NULL_OR_EMPTY =
    'LOGIN_SCREEN_PASSWORD_NOT_NULL_OR_EMPTY';

// IMAGES
const CONSTANT_IMAGES_APP_ICON = 'assets/images/app-icon.jpg';

// SERVER
const CONSTANT_SERVER_URL_NAME = 'CONSTANT_SERVER_URL_NAME';
