// ENV
const CONFIG_ENVIRONMENT_DEV = 'DEV';
const CONFIG_ENVIRONMENT_RELEASE = 'RELEASE';
const CONFIG_APP_NAME = 'APP_NAME';
const CONFIG_IS_DEBUG = 'IS_DEBUG';

// LOCALE
const CONFIG_STORE_LOCALE = 'LOCALE';

// LOCALES
const CONFIG_LOCALES_EN = 'assets/locales/en.json';
const CONFIG_LOCALES_VI = 'assets/locales/vi.json';

const LOCALES_ERROR_SOMETHING_WROMG = 'ERROR_SOMETHING_WROMG';
const LOCALES_HOME_TITLE = 'HOME_TITLE';
const LOCALES_LOGIN_TITLE = 'LOGIN_TITLE';

// IMAGES
const CONFIG_IMAGES_APP_ICON = 'assets/images/app-icon.jpg';

// SERVER
const CONFIG_SERVER_URL_NAME = 'CONFIG_SERVER_URL_NAME';
