// ENV
const CONSTANT_ENVIRONMENT_DEV = 'DEV';
const CONSTANT_ENVIRONMENT_RELEASE = 'RELEASE';
const CONSTANT_APP_NAME = 'APP_NAME';
const CONSTANT_IS_DEBUG = 'IS_DEBUG';

// LOCALE
const CONSTANT_STORE_LOCALE = 'LOCALE';

// LOCALES
const CONSTANT_LOCALES_EN = 'assets/locales/en.json';
const CONSTANT_LOCALES_VI = 'assets/locales/vi.json';

const CONSTANT_ERROR_SOMETHING_WROMG = 'ERROR_SOMETHING_WROMG';
const CONSTANT_LOGIN_SCREEN_NAME_HEADER = 'LOGIN_SCREEN_NAME_HEADER';
const CONSTANT_LOGIN_SCREEN_TITLE_USERNAME = 'LOGIN_SCREEN_TITLE_USERNAME';
const CONSTANT_LOGIN_SCREEN_TITLE_PASSWORD = 'LOGIN_SCREEN_TITLE_PASSWORD';
const CONSTANT_LOGIN_SCREEN_TITLE_REMEMBERME = 'LOGIN_SCREEN_TITLE_REMEMBERME';
const CONSTANT_LOGIN_SCREEN_TITLE_FORGOT_PASSWORD =
    'LOGIN_SCREEN_TITLE_FORGOT_PASSWORD';
const CONSTANT_LOGIN_SCREEN_NAME_BUTTON_LOGIN =
    'LOGIN_SCREEN_NAME_BUTTON_LOGIN';
const CONSTANT_LOGIN_SCREEN_TITLE_DONT_HAVE_AN_ACCOUNT_YET =
    'LOGIN_SCREEN_TITLE_DONT_HAVE_AN_ACCOUNT_YET';
const CONSTANT_LOGIN_SCREEN_TITLE_SIGN_UP_NOW =
    'LOGIN_SCREEN_TITLE_SIGN_UP_NOW';
const CONSTANT_LOGIN_SCREEN_USERNAME_NOT_NULL_OR_EMPTY =
    'LOGIN_SCREEN_USERNAME_NOT_NULL_OR_EMPTY';
const CONSTANT_LOGIN_SCREEN_PASSWORD_NOT_NULL_OR_EMPTY =
    'LOGIN_SCREEN_PASSWORD_NOT_NULL_OR_EMPTY';
const CONSTANT_LOGIN_SCREEN_USERNAME_OR_PASSWORD_FAILED =
    'LOGIN_SCREEN_USERNAME_OR_PASSWORD_FAILED';
const CONSTANT_HOME_SCREEN_TITLE_CHAT = 'HOME_SCREEN_TITLE_CHAT';
const CONSTANT_HOME_SCREEN_TITLE_SETTING = 'HOME_SCREEN_TITLE_SETTING';
const CONSTANT_LOGIN_SCREEN_TITLE_SIGN_IN = "LOGIN_SCREEN_TITLE_SIGN_IN";
const CONSTANT_LOGIN_SCREEN_TITLE_REGISTER = "LOGIN_SCREEN_TITLE_REGISTER";
const CONSTANT_LOGIN_SCREEN_TITLE_NEW_PASSWORD =
    "LOGIN_SCREEN_TITLE_NEW_PASSWORD";
const CONSTANT_LOGIN_SCREEN_TITLE_OLD_PASSWORD =
    "LOGIN_SCREEN_TITLE_OLD_PASSWORD";
const CONSTANT_LOGIN_SCREEN_TITLE_CONFIRM_PASSWORD =
    "LOGIN_SCREEN_TITLE_CONFIRM_PASSWORD";
const CONSTANT_CHATCONTENT_SCREEN_HINTTEXT_TYPE_SOMETHING =
    "CHATCONTENT_SCREEN_HINTTEXT_TYPE_SOMETHING";
const CONSTANT_CHATCONTENT_SCREEN_TITLE_IMAGE =
    "CHATCONTENT_SCREEN_TITLE_IMAGE";
const CONSTANT_CHATCONTENT_SCREEN_DESCRIPTION_IMAGE =
    "CHATCONTENT_SCREEN_DESCRIPTION_IMAGE";
const CONSTANT_CHATCONTENT_SCREEN_TITLE_FILE = "CHATCONTENT_SCREEN_TITLE_FILE";
const CONSTANT_CHATCONTENT_SCREEN_DESCRIPTION_FILE =
    "CHATCONTENT_SCREEN_DESCRIPTION_FILE";
const CONSTANT_CHATCONTENT_SCREEN_NO_MESSAGE = 'CHATCONTENT_SCREEN_NO_MESSAGE';

// IMAGES
const CONSTANT_IMAGES_APP_ICON = 'assets/images/app-icon.jpg';

// SERVER
const CONSTANT_SERVER_URL_NAME = 'CONSTANT_SERVER_URL_NAME';
